export const IndexButtonListData = [
    "All",
    "Music",
    "Gaming",
    "Tamil Cinema",
    "News",
    "Live",
    "Fashion",
    "Movies",
    "Courses",
    "Sports",
    "Trending",
    "Shopping",
    "National Geographic",
    "National Science",
    "Discovery UK",
    "Computer Programming",
    "Drama",
    "Comedy",
    "Science",
    "Technology",
    "Food",
    "Jukebox",
    "T-Series",
    "Sony Music",
    "Zee Music",
    "Tamil Music",
    "Watched",
    "Recently Added",
    "Liked",
    "Subscribed",
    "History",
    
]